[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Configuração específica para a função 'api'
[functions."api"]
  # Diz ao Netlify para não usar seu empacotador esbuild padrão
  # e sim usar um empacotador mais robusto (zip-it-and-ship-it)
  # que lida melhor com dependências complexas como as do Express/Vite.
  node_bundler = "zisi"

# Regra de redirecionamento para a API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200